/* NOTE: Select an exercise and use CTRL+MAYUS+C to comment it. Select an exercise and use CTRL+MAYUS+X to uncomment it. */

/*********************************************************
    Exercise 1
		Type in and run the nine programs presented in this chapter. Compare the output produced by each program with the output presented after each program in the text.
*********************************************************/

// The outputs are the same.

/*********************************************************
    Exercise 2
		Write a program to generate and display a table of n and n2, for integer values of n ranging from 1 to 10. Be certain to print appropriate column headings.
*********************************************************/

//#include <stdio.h>
//
//int main() {
//    int n = 0, a = 0;
//
//    printf("Please, enter a positive integer number ranging from 1 to 10: ");
//    scanf("%i", &n);
//
//    printf("\n");
//
//    for (a = 1; a <= n; a++) {
//        printf("Number: %3i       Number squared: %3i\n", a, a * a);
//    }
//
//    return 0;
//}

/*********************************************************
    Exercise 3
		A triangular number can also be generated by the formula

            triangularNumber = n * (n + 1) / 2

        for any integer value of n. For example, the 10th triangular number, 55, can be generated by substituting 10 as the value for n in the preceding formula.
        Write a program that generates a table of triangular numbers using the preceding formula.
        Have the program generate every fifth triangular number between 5 and 50 (that is, 5, 10, 15, ..., 50).
*********************************************************/

//#include <stdio.h>
//
//int main () {
//    // Can be made with ints too.
//
//    float a = 5.0F;
//
//    for ( ; a <= 50; a += 5)
//    {
//        printf("Value of triangular number %.3f: %.3f\n", a, a * (a + 1.0F) / 2.0F);
//    }
//}
